# Generated by Django 4.2.11 on 2024-04-07 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_groups_alter_user_user_permissions'),
        ('accounts', '0002_user_auth_provider'),
    ]

    operations = [
    ]
